name: news
description: Simple news app created for training purposes.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter_facebook_auth: ^3.5.2
  flutter_riverpod: ^0.14.0+3
  font_awesome_flutter: ^9.1.0
  freezed_annotation: ^0.14.0
#  github_sign_in: ^0.0.4
  google_sign_in: ^5.1.1
  http: ^0.13.3
  intl: ^0.17.0
  logger: ^1.1.0
  share_plus: ^3.0.4
  timeago: ^3.1.0
#  twitter_login: ^4.0.1
  webview_flutter: ^2.1.2
  xml: ^5.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  freezed: ^0.14.0
  json_serializable: ^6.0.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
