name: news
description: A constantly evolving news app created for training purposes.
publish_to: 'none'
version: 0.0.1
homepage: https://github.com/kostyan0005/news

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auth:
    path: packages/auth

  cloud_firestore: ^4.8.1
  easy_localization: ^3.0.2
  easy_logger: ^0.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.0.3
  go_router: ^4.1.0
  google_fonts: ^3.0.1
  http: ^0.13.3
  intl: 0.18.0
  json_annotation: ^4.3.0
  logger: ^1.1.0
  persistent_bottom_nav_bar: ^4.0.2
  pull_to_refresh: ^2.0.0
  share_plus: ^4.0.4
  timeago: ^3.1.0
  webview_flutter: ^3.0.0
  webview_flutter_web: ^0.1.0+1
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  build_runner: ^2.1.2
  fake_cloud_firestore: ^2.4.1+1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  json_serializable: ^6.0.0
  mocktail: ^0.3.0

flutter_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
