name: news
description: Simple news app created for training purposes.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auth:
    path: packages/auth

  cloud_firestore: ^3.1.7
  easy_localization: ^3.0.0
  firebase_auth: ^3.1.1
  firebase_core: ^1.12.0
  flutter_riverpod: ^1.0.0
  font_awesome_flutter: ^9.1.0
  freezed_annotation: ^1.0.0
  http: ^0.13.3
  intl: ^0.17.0
  json_annotation: ^4.3.0
  logger: ^1.1.0
  pull_to_refresh: ^2.0.0
  share_plus: ^3.0.4
  timeago: ^3.1.0
  webview_flutter: ^3.0.0
  xml: ^5.1.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  freezed: ^1.0.0
  json_serializable: ^6.0.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
