name: auth
description: A package providing authentication utilities.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.6.3
  flutter_facebook_auth: ^4.3.4
  flutter_riverpod: ^2.0.0-dev.3
  google_sign_in: ^5.1.1
  logger: ^1.1.0
  twitter_login: ^4.2.3

dev_dependencies:
  flutter_lints: ^2.0.1
