name: auth
description: A package providing authenticatiton utilities.
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^3.1.1
  flutter_facebook_auth: ^3.5.7
  flutter_riverpod: ^2.0.0-dev.3
  google_sign_in: ^5.1.1
  logger: ^1.1.0
  twitter_login: ^4.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
