name: auth
description: A package providing authenticatiton utilities.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: ^3.1.1
  flutter_facebook_auth: ^3.5.7
  flutter_riverpod: ^1.0.0
  google_sign_in: ^5.1.1
  logger: ^1.1.0
  twitter_login: ^4.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
