// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGf4Jm1I67lPZdr6ShqguqdkV5hWfSbCE',
    appId: '1:966196182204:android:5ce7f6eeba22a64fe2e4b9',
    messagingSenderId: '966196182204',
    projectId: 'news-prod-1',
    storageBucket: 'news-prod-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuSFnHfkyy94fxqWUzpCF_HeLP51ckoyM',
    appId: '1:966196182204:ios:bf65fa2b6238d7f9e2e4b9',
    messagingSenderId: '966196182204',
    projectId: 'news-prod-1',
    storageBucket: 'news-prod-1.appspot.com',
    androidClientId:
        '966196182204-j13o1spiuq2sapa499h3qgdom9rve4m0.apps.googleusercontent.com',
    iosClientId:
        '966196182204-pq6ndflam0tbr67ppvu13nhf068en62v.apps.googleusercontent.com',
    iosBundleId: 'com.kostiar.news',
  );
}
